name: qandaapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.00.00+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  dialog_flowtter: ^0.3.3

  modal_bottom_sheet: ^2.0.0
  get: ^4.6.1
  #  awesome_select: ^5.1.0
  google_fonts: 2.2.0
  intl: ^0.17.0
  basic_utils: ^4.2.0
#  direct_select_flutter: ^1.1.1
#  numberpicker: ^2.1.1
#  dropdown_button2: ^1.1.1
#  bot_toast: ^4.0.1

#  flutter_chat_ui: ^1.5.5

  #chat features
  file_picker: ^4.3.3
  image_picker: ^0.8.5
  mime: ^1.0.1
  open_file: ^3.2.1
  uuid: ^3.0.5
  #experiment
  flutter_tts: ^3.3.3
  speech_to_text: ^5.4.3
  group_button: ^5.0.0
  photo_view: ^0.13.0
  wakelock: ^0.6.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/dialog_flow_auth.json
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

